name: Validate Secret and Log Variable

on:
  push:
    branches:
      - '**'

jobs:
  validate-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate secret and log variable
        run: |
          # Definir el valor esperado del secreto
          EXPECTED_SECRET="valor_esperado"

          # Validar el secreto
          if [[ "$SECRET_VALUE" == "$EXPECTED_SECRET" ]]; then
            echo "El secreto es correcto."
          else
            echo "Error: El valor del secreto es incorrecto."
            exit 1
          fi

          # Mostrar el valor de una variable en los logs
          echo "El valor de la variable es: ${{ vars.MY_VARIABLE }}"
        env:
          SECRET_VALUE: ${{ secrets.MY_SECRET }}
